modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/starfish-studios/Naturalist/issues"
license = "MIT"

[[mods]]
modId = "naturalist"
version = "${version}"
displayName = "Naturalist"
authors = "Starfish Studios"
displayURL="https://www.curseforge.com/minecraft/mc-mods/naturalist"
description = '''
Enhances the overworld by adding new wildlife with unique behavior!
'''
logoFile = "icon.png"

[[dependencies.naturalist]]
modId = "forge"
mandatory = true
versionRange = "[41.0.98,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naturalist]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.naturalist]]
modId="geckolib"
mandatory=true
versionRange="[4.0.0,)"
ordering="NONE"
side="BOTH"